.PHONY: file-init
file-init:
	@mkdir -p /tmp/output

.PHONY: file-ci
file-ci: file-init
	docker run -v $(realpath ${GITHUB_WORKSPACE}):/src \
		cytopia/awesome-ci $(GIT_CI_TOOL) --path=/src --ignore=.git \
		> /tmp/output/$(GIT_CI_TOOL).txt
	@EXIT_CODE=$$?
	@cat /tmp/output/$(GIT_CI_TOOL).txt
	@exit $$EXIT_CODE
