services:
  node-api:
    build: ./node-api
    ports:
      - 3001:3000

  python-api:
    build: ./python-api
    ports:
      - 3002:5000

  ui:
    build: ./python-api
    ports:
      - 5000:3000
