TRIVY_VERSION ?= 0.2.1
TRIVY_IGNORE = $(realpath .trivyignore)

.PHONY: docker-audit-trivy
docker-audit-trivy: build
	mkdir -p /tmp/output
	docker run --rm \
		-v /tmp/scan:/root/.cache/ \
		-v /tmp/output:/output \
		-v $(TRIVY_IGNORE):/.trivyignore \
		-v /var/run/docker.sock:/var/run/docker.sock \
		aquasec/trivy:${TRIVY_VERSION} \
		--no-progress --exit-code 1 \
		-f json -o /output/trivy.json \
		--ignorefile /.trivyignore \
		 ${DOCKER_IMAGE}
	@cat /tmp/output/trivy.json
	@echo ""
