DOCKER_HASH := $(shell git rev-parse --short=8 HEAD)
DOCKER_REGISTRY ?= docker.pkg.github.com
DOCKER_IMAGE ?= app

REPO = $(DOCKER_REGISTRY)/$(GITHUB_REPOSITORY)/$(DOCKER_IMAGE):$(DOCKER_HASH)

.PHONY: publish-python
publish-python: build
	docker tag $(IMAGE) $(REPO)
	docker push $(REPO)
