DOCKER_IMAGE = example-ci/ui

include ../ci/Makefile.build
include ../ci/Makefile.test
include ../ci/Makefile.trivy-scan
include ../ci/Makefile.publish-npm
include ../ci/Makefile.publish-docker
include ../ci/Makefile.lint
