name: Awesome Project

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
    matrix:
      component: ['box-api-1', 'box-api-2', 'box-ui']
    steps:
    - uses: actions/checkout@v1
    - name: Test the component
      run: cd ${{ matrix.component }} && make test